require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProductionRunsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProductionRun. As you add validations to ProductionRun, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { lot_name: 'prod run', product_id: FactoryGirl.create(:product).id, producer_id: FactoryGirl.create(:producer).id }
  }

  let(:invalid_attributes) {
    { product_id: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductionRunsController. Be sure to keep this updated too.
  def valid_session 
    allow(controller).to receive_messages(:signed_in? => true)
  end


  describe "GET #index" do
    it "assigns all production_runs as @production_runs" do
      production_run = ProductionRun.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:production_runs)).to eq([production_run])
    end
  end

  describe "GET #show" do
    it "assigns the requested production_run as @production_run" do
      production_run = ProductionRun.create! valid_attributes
      get :show, {:id => production_run.to_param}, valid_session
      expect(assigns(:production_run)).to eq(production_run)
    end
  end

  describe "GET #new" do
    it "assigns a new production_run as @production_run" do
      get :new, {}, valid_session
      expect(assigns(:production_run)).to be_a_new(ProductionRun)
    end
  end

  describe "GET #edit" do
    it "assigns the requested production_run as @production_run" do
      production_run = ProductionRun.create! valid_attributes
      get :edit, {:id => production_run.to_param}, valid_session
      expect(assigns(:production_run)).to eq(production_run)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ProductionRun" do
        expect {
          post :create, {:production_run => valid_attributes}, valid_session
        }.to change(ProductionRun, :count).by(1)
      end

      it "assigns a newly created production_run as @production_run" do
        post :create, {:production_run => valid_attributes}, valid_session
        expect(assigns(:production_run)).to be_a(ProductionRun)
        expect(assigns(:production_run)).to be_persisted
      end

      it "redirects to the created production_run" do
        post :create, {:production_run => valid_attributes}, valid_session
        expect(response).to redirect_to(ProductionRun.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved production_run as @production_run" do
        post :create, {:production_run => invalid_attributes}, valid_session
        expect(assigns(:production_run)).to be_a_new(ProductionRun)
      end

      it "re-renders the 'new' template" do
        post :create, {:production_run => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { lot_name: "new run" }
      }

      it "updates the requested production_run" do
        production_run = ProductionRun.create! valid_attributes
        put :update, {:id => production_run.to_param, :production_run => new_attributes}, valid_session
        production_run.reload
        expect(production_run.lot_name).to eql('new run')
      end

      it "assigns the requested production_run as @production_run" do
        production_run = ProductionRun.create! valid_attributes
        put :update, {:id => production_run.to_param, :production_run => valid_attributes}, valid_session
        expect(assigns(:production_run)).to eq(production_run)
      end

      it "redirects to the production_run" do
        production_run = ProductionRun.create! valid_attributes
        put :update, {:id => production_run.to_param, :production_run => valid_attributes}, valid_session
        expect(response).to redirect_to(production_run)
      end
    end

    context "with invalid params" do
      it "assigns the production_run as @production_run" do
        production_run = ProductionRun.create! valid_attributes
        put :update, {:id => production_run.to_param, :production_run => invalid_attributes}, valid_session
        expect(assigns(:production_run)).to eq(production_run)
      end

      it "re-renders the 'edit' template" do
        production_run = ProductionRun.create! valid_attributes
        put :update, {:id => production_run.to_param, :production_run => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested production_run" do
      production_run = ProductionRun.create! valid_attributes
      expect {
        delete :destroy, {:id => production_run.to_param}, valid_session
      }.to change(ProductionRun, :count).by(-1)
    end

    it "redirects to the production_runs list" do
      production_run = ProductionRun.create! valid_attributes
      delete :destroy, {:id => production_run.to_param}, valid_session
      expect(response).to redirect_to(production_runs_url)
    end
  end

end
