require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProductShipmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProductShipment. As you add validations to ProductShipment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { product_id: FactoryGirl.create(:product).id,
      customer_id: FactoryGirl.create(:customer).id }
  }

  let(:invalid_attributes) {
    { customer_id: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductShipmentsController. Be sure to keep this updated too.
  def valid_session
    allow(controller).to receive_messages(:signed_in? => true)
  end


  describe "GET #index" do
    it "assigns all product_shipments as @product_shipments" do
      product_shipment = ProductShipment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:product_shipments)).to eq([product_shipment])
    end
  end

  describe "GET #show" do
    it "assigns the requested product_shipment as @product_shipment" do
      product_shipment = ProductShipment.create! valid_attributes
      get :show, {:id => product_shipment.to_param}, valid_session
      expect(assigns(:product_shipment)).to eq(product_shipment)
    end
  end

  describe "GET #new" do
    it "assigns a new product_shipment as @product_shipment" do
      get :new, {}, valid_session
      expect(assigns(:product_shipment)).to be_a_new(ProductShipment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested product_shipment as @product_shipment" do
      product_shipment = ProductShipment.create! valid_attributes
      get :edit, {:id => product_shipment.to_param}, valid_session
      expect(assigns(:product_shipment)).to eq(product_shipment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ProductShipment" do
        expect {
          post :create, {:product_shipment => valid_attributes}, valid_session
        }.to change(ProductShipment, :count).by(1)
      end

      it "assigns a newly created product_shipment as @product_shipment" do
        post :create, {:product_shipment => valid_attributes}, valid_session
        expect(assigns(:product_shipment)).to be_a(ProductShipment)
        expect(assigns(:product_shipment)).to be_persisted
      end

      it "redirects to the created product_shipment" do
        post :create, {:product_shipment => valid_attributes}, valid_session
        expect(response).to redirect_to(ProductShipment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved product_shipment as @product_shipment" do
        post :create, {:product_shipment => invalid_attributes}, valid_session
        expect(assigns(:product_shipment)).to be_a_new(ProductShipment)
      end

      it "re-renders the 'new' template" do
        post :create, {:product_shipment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { order_amount: 100 }
      }

      it "updates the requested product_shipment" do
        product_shipment = ProductShipment.create! valid_attributes
        put :update, {:id => product_shipment.to_param, :product_shipment => new_attributes}, valid_session
        product_shipment.reload
        expect(product_shipment.order_amount).to eql(100)
      end

      it "assigns the requested product_shipment as @product_shipment" do
        product_shipment = ProductShipment.create! valid_attributes
        put :update, {:id => product_shipment.to_param, :product_shipment => valid_attributes}, valid_session
        expect(assigns(:product_shipment)).to eq(product_shipment)
      end

      it "redirects to the product_shipment" do
        product_shipment = ProductShipment.create! valid_attributes
        put :update, {:id => product_shipment.to_param, :product_shipment => valid_attributes}, valid_session
        expect(response).to redirect_to(product_shipment)
      end
    end

    context "with invalid params" do
      it "assigns the product_shipment as @product_shipment" do
        product_shipment = ProductShipment.create! valid_attributes
        put :update, {:id => product_shipment.to_param, :product_shipment => invalid_attributes}, valid_session
        expect(assigns(:product_shipment)).to eq(product_shipment)
      end

      it "re-renders the 'edit' template" do
        product_shipment = ProductShipment.create! valid_attributes
        put :update, {:id => product_shipment.to_param, :product_shipment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested product_shipment" do
      product_shipment = ProductShipment.create! valid_attributes
      expect {
        delete :destroy, {:id => product_shipment.to_param}, valid_session
      }.to change(ProductShipment, :count).by(-1)
    end

    it "redirects to the product_shipments list" do
      product_shipment = ProductShipment.create! valid_attributes
      delete :destroy, {:id => product_shipment.to_param}, valid_session
      expect(response).to redirect_to(product_shipments_url)
    end
  end

end
