require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SuppliesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Supply. As you add validations to Supply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'supply' }
  }

  let(:invalid_attributes) {
    { name: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SuppliesController. Be sure to keep this updated too.
  def valid_session 
    allow(controller).to receive_messages(:signed_in? => true)
  end

  describe "GET #index" do
    it "assigns all supplies as @supplies" do
      supply = Supply.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:supplies)).to eq([supply])
    end
  end

  describe "GET #show" do
    it "assigns the requested supply as @supply" do
      supply = Supply.create! valid_attributes
      get :show, {:id => supply.to_param}, valid_session
      expect(assigns(:supply)).to eq(supply)
    end
  end

  describe "GET #new" do
    it "assigns a new supply as @supply" do
      get :new, {}, valid_session
      expect(assigns(:supply)).to be_a_new(Supply)
    end
  end

  describe "GET #edit" do
    it "assigns the requested supply as @supply" do
      supply = Supply.create! valid_attributes
      get :edit, {:id => supply.to_param}, valid_session
      expect(assigns(:supply)).to eq(supply)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Supply" do
        expect {
          post :create, {:supply => valid_attributes}, valid_session
        }.to change(Supply, :count).by(1)
      end

      it "assigns a newly created supply as @supply" do
        post :create, {:supply => valid_attributes}, valid_session
        expect(assigns(:supply)).to be_a(Supply)
        expect(assigns(:supply)).to be_persisted
      end

      it "redirects to the created supply" do
        post :create, {:supply => valid_attributes}, valid_session
        expect(response).to redirect_to(Supply.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved supply as @supply" do
        post :create, {:supply => invalid_attributes}, valid_session
        expect(assigns(:supply)).to be_a_new(Supply)
      end

      it "re-renders the 'new' template" do
        post :create, {:supply => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'new supply' }
      }

      it "updates the requested supply" do
        supply = Supply.create! valid_attributes
        put :update, {:id => supply.to_param, :supply => new_attributes}, valid_session
        supply.reload
        expect(supply.name).to eql('new supply')
      end

      it "assigns the requested supply as @supply" do
        supply = Supply.create! valid_attributes
        put :update, {:id => supply.to_param, :supply => valid_attributes}, valid_session
        expect(assigns(:supply)).to eq(supply)
      end

      it "redirects to the supply" do
        supply = Supply.create! valid_attributes
        put :update, {:id => supply.to_param, :supply => valid_attributes}, valid_session
        expect(response).to redirect_to(supply)
      end
    end

    context "with invalid params" do
      it "assigns the supply as @supply" do
        supply = Supply.create! valid_attributes
        put :update, {:id => supply.to_param, :supply => invalid_attributes}, valid_session
        expect(assigns(:supply)).to eq(supply)
      end

      it "re-renders the 'edit' template" do
        supply = Supply.create! valid_attributes
        put :update, {:id => supply.to_param, :supply => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested supply" do
      supply = Supply.create! valid_attributes
      expect {
        delete :destroy, {:id => supply.to_param}, valid_session
      }.to change(Supply, :count).by(-1)
    end

    it "redirects to the supplies list" do
      supply = Supply.create! valid_attributes
      delete :destroy, {:id => supply.to_param}, valid_session
      expect(response).to redirect_to(supplies_url)
    end
  end

end
