require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SupplyConsumptionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SupplyConsumption. As you add validations to SupplyConsumption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { supply_id: FactoryGirl.create(:supply).id, 
      production_run_id: FactoryGirl.create(:production_run).id }
  }

  let(:invalid_attributes) {
    { production_run_id: nil, supply_id: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplyConsumptionsController. Be sure to keep this updated too.
  def valid_session 
    allow(controller).to receive_messages(:signed_in? => true)
  end

  describe "GET #index" do
    it "assigns all supply_consumptions as @supply_consumptions" do
      supply_consumption = SupplyConsumption.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:supply_consumptions)).to eq([supply_consumption])
    end
  end

  describe "GET #show" do
    it "assigns the requested supply_consumption as @supply_consumption" do
      supply_consumption = SupplyConsumption.create! valid_attributes
      get :show, {:id => supply_consumption.to_param}, valid_session
      expect(assigns(:supply_consumption)).to eq(supply_consumption)
    end
  end

  describe "GET #new" do
    it "assigns a new supply_consumption as @supply_consumption" do
      get :new, {}, valid_session
      expect(assigns(:supply_consumption)).to be_a_new(SupplyConsumption)
    end
  end

  describe "GET #edit" do
    it "assigns the requested supply_consumption as @supply_consumption" do
      supply_consumption = SupplyConsumption.create! valid_attributes
      get :edit, {:id => supply_consumption.to_param}, valid_session
      expect(assigns(:supply_consumption)).to eq(supply_consumption)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SupplyConsumption" do
        expect {
          post :create, {:supply_consumption => valid_attributes}, valid_session
        }.to change(SupplyConsumption, :count).by(1)
      end

      it "assigns a newly created supply_consumption as @supply_consumption" do
        post :create, {:supply_consumption => valid_attributes}, valid_session
        expect(assigns(:supply_consumption)).to be_a(SupplyConsumption)
        expect(assigns(:supply_consumption)).to be_persisted
      end

      it "redirects to the created supply_consumption" do
        post :create, {:supply_consumption => valid_attributes}, valid_session
        expect(response).to redirect_to(SupplyConsumption.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved supply_consumption as @supply_consumption" do
        post :create, {:supply_consumption => invalid_attributes}, valid_session
        expect(assigns(:supply_consumption)).to be_a_new(SupplyConsumption)
      end

      it "re-renders the 'new' template" do
        post :create, {:supply_consumption => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { used_amount: 10 }
      }

      it "updates the requested supply_consumption" do
        supply_consumption = SupplyConsumption.create! valid_attributes
        put :update, {:id => supply_consumption.to_param, :supply_consumption => new_attributes}, valid_session
        supply_consumption.reload
        expect(supply_consumption.used_amount).to eql(10)
      end

      it "assigns the requested supply_consumption as @supply_consumption" do
        supply_consumption = SupplyConsumption.create! valid_attributes
        put :update, {:id => supply_consumption.to_param, :supply_consumption => valid_attributes}, valid_session
        expect(assigns(:supply_consumption)).to eq(supply_consumption)
      end

      it "redirects to the supply_consumption" do
        supply_consumption = SupplyConsumption.create! valid_attributes
        put :update, {:id => supply_consumption.to_param, :supply_consumption => valid_attributes}, valid_session
        expect(response).to redirect_to(supply_consumption)
      end
    end

    context "with invalid params" do
      it "assigns the supply_consumption as @supply_consumption" do
        supply_consumption = SupplyConsumption.create! valid_attributes
        put :update, {:id => supply_consumption.to_param, :supply_consumption => invalid_attributes}, valid_session
        expect(assigns(:supply_consumption)).to eq(supply_consumption)
      end

      it "re-renders the 'edit' template" do
        supply_consumption = SupplyConsumption.create! valid_attributes
        put :update, {:id => supply_consumption.to_param, :supply_consumption => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested supply_consumption" do
      supply_consumption = SupplyConsumption.create! valid_attributes
      expect {
        delete :destroy, {:id => supply_consumption.to_param}, valid_session
      }.to change(SupplyConsumption, :count).by(-1)
    end

    it "redirects to the supply_consumptions list" do
      supply_consumption = SupplyConsumption.create! valid_attributes
      delete :destroy, {:id => supply_consumption.to_param}, valid_session
      expect(response).to redirect_to(supply_consumptions_url)
    end
  end

end
