require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SupplyShipmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SupplyShipment. As you add validations to SupplyShipment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    supply = Supply.create!(name: 'my name')
    supplier = Supplier.create!(name: 'my name')
    { supply_id: supply.id, supplier_id: supplier.id }
  }

  let(:invalid_attributes) {
    { supply_id: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplyShipmentsController. Be sure to keep this updated too.
  def valid_session 
    allow(controller).to receive_messages(:signed_in? => true)
  end


  describe "GET #index" do
    it "assigns all supply_shipments as @supply_shipments" do
      supply_shipment = SupplyShipment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:supply_shipments)).to eq([supply_shipment])
    end
  end

  describe "GET #show" do
    it "assigns the requested supply_shipment as @supply_shipment" do
      supply_shipment = SupplyShipment.create! valid_attributes
      get :show, {:id => supply_shipment.to_param}, valid_session
      expect(assigns(:supply_shipment)).to eq(supply_shipment)
    end
  end

  describe "GET #new" do
    it "assigns a new supply_shipment as @supply_shipment" do
      get :new, {}, valid_session
      expect(assigns(:supply_shipment)).to be_a_new(SupplyShipment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested supply_shipment as @supply_shipment" do
      supply_shipment = SupplyShipment.create! valid_attributes
      get :edit, {:id => supply_shipment.to_param}, valid_session
      expect(assigns(:supply_shipment)).to eq(supply_shipment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SupplyShipment" do
        expect {
          post :create, {:supply_shipment => valid_attributes}, valid_session
        }.to change(SupplyShipment, :count).by(1)
      end

      it "assigns a newly created supply_shipment as @supply_shipment" do
        post :create, {:supply_shipment => valid_attributes}, valid_session
        expect(assigns(:supply_shipment)).to be_a(SupplyShipment)
        expect(assigns(:supply_shipment)).to be_persisted
      end

      it "redirects to the created supply_shipment" do
        post :create, {:supply_shipment => valid_attributes}, valid_session
        expect(response).to redirect_to(SupplyShipment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved supply_shipment as @supply_shipment" do
        post :create, {:supply_shipment => invalid_attributes}, valid_session
        expect(assigns(:supply_shipment)).to be_a_new(SupplyShipment)
      end

      it "re-renders the 'new' template" do
        post :create, {:supply_shipment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { order_amount: 100 }
      }

      it "updates the requested supply_shipment" do
        supply_shipment = SupplyShipment.create! valid_attributes
        put :update, {:id => supply_shipment.to_param, :supply_shipment => new_attributes}, valid_session
        supply_shipment.reload
        expect(supply_shipment.order_amount).to eql(100)
      end

      it "assigns the requested supply_shipment as @supply_shipment" do
        supply_shipment = SupplyShipment.create! valid_attributes
        put :update, {:id => supply_shipment.to_param, :supply_shipment => valid_attributes}, valid_session
        expect(assigns(:supply_shipment)).to eq(supply_shipment)
      end

      it "redirects to the supply_shipment" do
        supply_shipment = SupplyShipment.create! valid_attributes
        put :update, {:id => supply_shipment.to_param, :supply_shipment => valid_attributes}, valid_session
        expect(response).to redirect_to(supply_shipment)
      end
    end

    context "with invalid params" do
      it "assigns the supply_shipment as @supply_shipment" do
        supply_shipment = SupplyShipment.create! valid_attributes
        put :update, {:id => supply_shipment.to_param, :supply_shipment => invalid_attributes}, valid_session
        expect(assigns(:supply_shipment)).to eq(supply_shipment)
      end

      it "re-renders the 'edit' template" do
        supply_shipment = SupplyShipment.create! valid_attributes
        put :update, {:id => supply_shipment.to_param, :supply_shipment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested supply_shipment" do
      supply_shipment = SupplyShipment.create! valid_attributes
      expect {
        delete :destroy, {:id => supply_shipment.to_param}, valid_session
      }.to change(SupplyShipment, :count).by(-1)
    end

    it "redirects to the supply_shipments list" do
      supply_shipment = SupplyShipment.create! valid_attributes
      delete :destroy, {:id => supply_shipment.to_param}, valid_session
      expect(response).to redirect_to(supply_shipments_url)
    end
  end

end
